version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: defaultpassword
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5432:5432"
